-- MySQL Script generated by MySQL Workbench
-- 08/09/14 11:39:41
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test_db_info
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_db_info` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `test_db_info` ;

-- -----------------------------------------------------
-- Table `test_db_info`.`hello`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_db_info`.`hello` ;

CREATE TABLE IF NOT EXISTS `test_db_info`.`hello` (
  `id` INT NOT NULL,
  `comment` TEXT NULL,
  `vakue` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
